# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v3.7.2-6-g6f85411
_src_path: djereo
author_email: alberto.moronh@gmail.com
author_name: Alberto Morón Hernández
django_version: '5.2'
is_github_project: true
postgres_version: '17'
project_name: suydtdjereo
python_version: '3.12'
use_django_waffle: true
use_htmx: true
