default_language_version:
  python: python3.12
  # Pin Node LTS for Biome
  node: 22.11.0
default_install_hook_types: ["commit-msg", "pre-commit"]
default_stages: ["pre-commit"]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: no-commit-to-branch
      - id: trailing-whitespace
        args: ["--markdown-linebreak-ext", "md"]
      - id: check-case-conflict

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.19.1
    hooks:
      - id: pyupgrade
        args: ["--py312-plus"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        exclude: '\.pdbrc$'

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.0
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format

  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.17.2
    hooks:
      - id: markdownlint-cli2
        args: ["--config", ".markdownlint-cli2.yaml"]

  - repo: https://github.com/biomejs/pre-commit
    rev: v1.9.4
    hooks:
      - id: biome-check
        exclude: '.*htmx.*\.min\.js'

  - repo: https://github.com/adamchainz/djade-pre-commit
    rev: 1.3.2
    hooks:
      - id: djade
        args: [--target-version, "5.1"]

  - repo: https://github.com/adamchainz/django-upgrade
    rev: 1.23.1
    hooks:
      - id: django-upgrade
        args: [--target-version, "5.1"]

  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.22.0
    hooks:
      - id: commitlint
        stages: ["commit-msg"]
        additional_dependencies: ["@commitlint/config-conventional"]
