# Pull Request pipeline
# Runs when a commit on a feature branch is pushed up to GitHub.
name: PR

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches-ignore:
      - main

jobs:
  checks:
    uses: ./.github/workflows/_pre-build-checks.yaml

  e2e_pydoll:
    needs: checks
    runs-on: ubuntu-24.04
    env:
      USE_ENV_TEST: "1"
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_DB: suydtdjereo
          POSTGRES_USER: suydtdjereo
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v5
      - uses: astral-sh/setup-uv@v6
        with:
          version: "0.6.17"
      - uses: extractions/setup-just@v3
      # install Chromium
      - run: sudo apt-get update
      - run: sudo apt-get install -y chromium-browser
      # run e2e tests
      - run: uv sync --group=test
      - run: just manage migrate
      - run: just manage seed_database
      - run: just runserver "" & # launch Django in background
      - run: sleep 5
      - run: uv run pytest tests_e2e/pydoll_e2e/
