# Release Please pipeline
# Refreshes a pull request that updates the changelog & bumps the Semantic Version every
# time the `main` branch is merged to.
# N.B. conventional commits (as enforced by the relevant git hook) are a prerequisite for
# Release Please to generate changelogs and calculate new SemVer tags.
name: release-please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-24.04
    steps:
      - id: release
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          config-file: .release-please-config.json
          manifest-file: .release-please-manifest.json
      # Update the version in uv.lock only if release-please created or updated a Pull Request.
      # Otherwise the 'checkout' step fails because the 'release-...' branch does not exist.
      # Avoids attempting a uv.lock update immediately after a release-please PR is merged.
      - uses: actions/checkout@v4
        if: ${{ steps.release.outputs.prs_created == 'true' }}
        with:
          ref: release-please--branches--main
      - uses: astral-sh/setup-uv@v6
        if: ${{ steps.release.outputs.prs_created == 'true' }}
        with:
          version: "0.6.4"
      - run: uv lock
        if: ${{ steps.release.outputs.prs_created == 'true' }}
        shell: bash
      - uses: stefanzweifel/git-auto-commit-action@v5
        if: ${{ steps.release.outputs.prs_created == 'true' }}
        with:
          file_pattern: 'uv.lock'
          commit_message: 'chore: update uv.lock with new version from release-please'
